name = "plat-telegram-bot"
main = "src/worker.js"
compatibility_date = "2026-06-13"
workers_dev = false

routes = [
  { pattern = "bot.edel.kz", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "plat_telegram"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
