name = "plat-telegram-bot"
main = "src/worker.js"
compatibility_date = "2026-06-13"
workers_dev = false

routes = [
  { pattern = "bot.michael.kz", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "plat_telegram"
database_id = "e9450fe2-08cc-4f04-b9d9-14e9ce6d0c8b"
